#ifndef CONFIG_H
#define CONFIG_H

// TODO -- change to static variables instead of macros

#define MUTATION_RATE_ADD_NODE 0.005
#define MUTATION_RATE_ADD_CONNECTION 0.005
#define MUTATION_RATE_PERTURB_BIAS 0.05
#define MUTATION_RATE_PERTURB_WEIGHT 0.05
#define MUTATION_RATE_TOGGLE_NODE 0.0005
#define MUTATION_RATE_TOGGLE_CONNECTION 0.0005

#define NODE_GENE_MAX_BIAS_PERTURBATION 1.0

#define CONNECTION_GENE_INITIAL_WEIGHT 0.0
#define CONNECTION_GENE_MAX_WEIGHT_PERTURBATION 1.0

#define GENOME_NUM_INPUT_NODES 16
#define GENOME_NUM_OUTPUT_NODES 4

#define POPULATION_SIZE 300
#define POPULATION_PURGE_COUNT 30
#define POPULATION_MAX_GENERATION 10000
#define POPULATION_MAX_GENOME_FITNESS 500.0
#define POPULATION_SPECIES_MAX_STAGNATION 20

#define VERBOSE_LOG false
#define RESET_AT_MAX_GENERATION true

#define GENOME_COMPATIBILITY_COEFFICIENT_ONE 1.0
#define GENOME_COMPATIBILITY_COEFFICIENT_TWO 1.0
#define GENOME_COMPATIBILITY_COEFFICIENT_THREE 1.0
#define GENOME_COMPATIBILITY_THRESHOLD 4.0

#endif